import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { TransactionWhereInputObjectSchema as TransactionWhereInputObjectSchema } from './objects/TransactionWhereInput.schema';
import { TransactionOrderByWithAggregationInputObjectSchema as TransactionOrderByWithAggregationInputObjectSchema } from './objects/TransactionOrderByWithAggregationInput.schema';
import { TransactionScalarWhereWithAggregatesInputObjectSchema as TransactionScalarWhereWithAggregatesInputObjectSchema } from './objects/TransactionScalarWhereWithAggregatesInput.schema';
import { TransactionScalarFieldEnumSchema } from './enums/TransactionScalarFieldEnum.schema';
import { TransactionCountAggregateInputObjectSchema as TransactionCountAggregateInputObjectSchema } from './objects/TransactionCountAggregateInput.schema';
import { TransactionMinAggregateInputObjectSchema as TransactionMinAggregateInputObjectSchema } from './objects/TransactionMinAggregateInput.schema';
import { TransactionMaxAggregateInputObjectSchema as TransactionMaxAggregateInputObjectSchema } from './objects/TransactionMaxAggregateInput.schema';
import { TransactionAvgAggregateInputObjectSchema as TransactionAvgAggregateInputObjectSchema } from './objects/TransactionAvgAggregateInput.schema';
import { TransactionSumAggregateInputObjectSchema as TransactionSumAggregateInputObjectSchema } from './objects/TransactionSumAggregateInput.schema';

export const TransactionGroupBySchema: z.ZodType<Prisma.TransactionGroupByArgs> = z.object({ where: TransactionWhereInputObjectSchema.optional(), orderBy: z.union([TransactionOrderByWithAggregationInputObjectSchema, TransactionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TransactionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TransactionScalarFieldEnumSchema), _count: z.union([ z.literal(true), TransactionCountAggregateInputObjectSchema ]).optional(), _min: TransactionMinAggregateInputObjectSchema.optional(), _max: TransactionMaxAggregateInputObjectSchema.optional(), _avg: TransactionAvgAggregateInputObjectSchema.optional(), _sum: TransactionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TransactionGroupByArgs>;

export const TransactionGroupByZodSchema = z.object({ where: TransactionWhereInputObjectSchema.optional(), orderBy: z.union([TransactionOrderByWithAggregationInputObjectSchema, TransactionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TransactionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TransactionScalarFieldEnumSchema), _count: z.union([ z.literal(true), TransactionCountAggregateInputObjectSchema ]).optional(), _min: TransactionMinAggregateInputObjectSchema.optional(), _max: TransactionMaxAggregateInputObjectSchema.optional(), _avg: TransactionAvgAggregateInputObjectSchema.optional(), _sum: TransactionSumAggregateInputObjectSchema.optional() }).strict();